require_relative './pipeline/regex_constants'
require_relative './pipeline/branch'
require_relative './pipeline/version_helper'
require_relative './pipeline/git_utils'
require_relative './pipeline/command/get_version'
require_relative './pipeline/command/branch_name'
